In [1]:
import pandas as pd

In [3]:
DF = pd.read_excel ("Student1.xlsx")

In [4]:
DF

      name  age      city   id
0  Sarvesh   20      pune  101
1    Dhanu   20   jalgaon  102
2   Pranav   27  parbhani  103
3   Sushil   21   Jalgaon  104
4    Tejas   25     Latur  105
5  Bhushan   23      pune  106
6   Vishal   26    Mumbai  107
7   Sanket   31     delhi  108
8     yash   52    bhopal  109
9   Sakshi   22  bhusaval  110

In [7]:
DF.sample (5) # each time select random data

      name  age      city   id
8     yash   52    bhopal  109
9   Sakshi   22  bhusaval  110
0  Sarvesh   20      pune  101
2   Pranav   27  parbhani  103
5  Bhushan   23      pune  106

In [8]:
DF.sample (5)

      name  age      city   id
8     yash   52    bhopal  109
0  Sarvesh   20      pune  101
1    Dhanu   20   jalgaon  102
6   Vishal   26    Mumbai  107
2   Pranav   27  parbhani  103

In [9]:
DF.sample (5)

     name  age      city   id
6  Vishal   26    Mumbai  107
9  Sakshi   22  bhusaval  110
2  Pranav   27  parbhani  103
1   Dhanu   20   jalgaon  102
7  Sanket   31     delhi  108