In [1]:
import pandas as pd

In [3]:
DF = pd.read_excel ("Student1.xlsx")

In [4]:
DF

      name  age      city   id
0  Sarvesh   20      pune  101
1    Dhanu   20   jalgaon  102
2   Pranav   27  parbhani  103
3   Sushil   21   Jalgaon  104
4    Tejas   25     Latur  105
5  Bhushan   23      pune  106
6   Vishal   26    Mumbai  107
7   Sanket   31     delhi  108
8     yash   52    bhopal  109
9   Sakshi   22  bhusaval  110

In [5]:
DF ['Salary'] = [10000,5000,30000,20000,34000,
                55000,43000,3000,12000,67000]

In [6]:
DF

      name  age      city   id  Salary
0  Sarvesh   20      pune  101   10000
1    Dhanu   20   jalgaon  102    5000
2   Pranav   27  parbhani  103   30000
3   Sushil   21   Jalgaon  104   20000
4    Tejas   25     Latur  105   34000
5  Bhushan   23      pune  106   55000
6   Vishal   26    Mumbai  107   43000
7   Sanket   31     delhi  108    3000
8     yash   52    bhopal  109   12000
9   Sakshi   22  bhusaval  110   67000

In [7]:
DF ["Bonous"] = DF["Salary"] * 10 / 100

In [8]:
DF

      name  age      city   id  Salary  Bonous
0  Sarvesh   20      pune  101   10000  1000.0
1    Dhanu   20   jalgaon  102    5000   500.0
2   Pranav   27  parbhani  103   30000  3000.0
3   Sushil   21   Jalgaon  104   20000  2000.0
4    Tejas   25     Latur  105   34000  3400.0
5  Bhushan   23      pune  106   55000  5500.0
6   Vishal   26    Mumbai  107   43000  4300.0
7   Sanket   31     delhi  108    3000   300.0
8     yash   52    bhopal  109   12000  1200.0
9   Sakshi   22  bhusaval  110   67000  6700.0

In [ ]:
DF.to_excel ("S2.xlsx" , index = False)